[workspace]
resolver = "2"
members = [
    "day01",
    "day02",
    "day03",
]

[workspace.package]
version = "0.0.0"

[workspace.dependencies]
clap = { version = "4.4.11", features = ["derive"] }
once_cell = "1.18.0"
regex = "1.10.2"